version: '3.1'

services:
  postgres:
    image: postgres:latest
    container_name: pgdb
    environment:
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"

  image_storage:
    build:
      context: .
      dockerfile: Dockerfile_storage
    volumes:
      - ./images:/app/images
    ports:
      - "8082:80"
